export enum taqTypes {
  user = "user",
  department = "department",
  faculty = "faculty",
  admin = "admin",
  academicFaculty = "academci_faculty",
  academicSemester = "academic_semester",
  academicDepartment = "academic_department",
  student = "student",
  room = "room",
  building = "building",
  course = "course",
  semesterRegistration = "semester-registration",
  courseRegistration = "courseRegistration",
  offeredCourses = "offeredCourses",
  offeredCourseSection = "offeredCourseSection",
}
export const tagTypesList = [
  taqTypes.user,
  taqTypes.department,
  taqTypes.faculty,
  taqTypes.admin,
  taqTypes.academicFaculty,
  taqTypes.academicSemester,
  taqTypes.academicDepartment,
  taqTypes.student,
  taqTypes.room,
  taqTypes.building,
  taqTypes.course,
  taqTypes.semesterRegistration,
  taqTypes.courseRegistration,
  taqTypes.offeredCourses,
  taqTypes.offeredCourseSection,
];
